name: booking_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dio: ^5.7.0
  flutter:
    sdk: flutter
  go_router: ^14.4.1
  google_maps_flutter: ^2.9.0
  google_maps_flutter_android: ^2.14.11
  google_maps_flutter_ios: ^2.13.1
  google_maps_flutter_web: ^0.5.10
  jwt_decoder: ^2.0.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
